name: 'Deploy Repository via rsync'
description: 'A custom action to deploy a repository to a remote server using rsync.'

inputs:
  ssh_user:
    description: 'The SSH username'
    required: true
  ssh_password:
    description: 'The SSH password'
    required: true
  remote_host:
    description: 'The remote host (IP or domain)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y rsync sshpass

    ## create ignore_files.txt for files to ignore in tar file
    - name: Create ignore file for exclusions
      shell: bash
      run: |
          echo "ignore_files.txt" >> ignore_files.txt
          echo "output/" >> ignore_files.txt
          echo ".gitignore" >> ignore_files.txt
          echo ".git" > ignore_files.txt
          echo ".github" >> ignore_files.txt
          echo "Thumbs.db" >> ignore_files.txt
          echo "wp-config.php" >> ignore_files.txt
          echo "wp-content/uploads/" >> ignore_files.txt
          echo "wp-content/mu-plugins/" >> ignore_files.txt

      # Step 4: Create a tar file using the ignore file
    - name: Create tar file
      shell: bash
      env:
        TAR_FILE: "./output/repository.tar.gz"
      run: |
          mkdir -p output
          tar --exclude-from=ignore_files.txt -czf "$TAR_FILE" .

    - name: Add remote host to known_hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ inputs.remote_host }} >> ~/.ssh/known_hosts

    - name: Deploy files via rsync
      shell: bash
      env:
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_PASSWORD: ${{ inputs.ssh_password }}
        REMOTE_HOST: ${{ inputs.remote_host }}
        REMOTE_DIR: '/html/deployer'
        TAR_FILE: "./output/repository.tar.gz"
      run: |
        ## create deployer DIR
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$REMOTE_HOST "mkdir -p '$REMOTE_DIR'"
        ## upload zip file
        sshpass -p "$SSH_PASSWORD" rsync -avz --delete "$TAR_FILE" "$SSH_USER"@"$REMOTE_HOST":"$REMOTE_DIR"

