name: 'Deploy Repository via rsync'
description: 'A custom action to deploy a repository to a remote server using rsync.'

inputs:
  ssh_user:
    description: 'The SSH username'
    required: true
  ssh_password:
    description: 'The SSH password'
    required: true
  remote_host:
    description: 'The remote host (IP or domain)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      with:
        path: git_checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -q && sudo apt-get install -y rsync sshpass

    - name: Create ignore file for exclusions
      shell: bash
      env:
        IGNORE_FILE: "output/ignore_files.txt"
      run: |
        mkdir -p output
        ls -lha .github
        ls -lha .github/actions
        cp .github/actions/ignorefiles.txt $IGNORE_FILE
        echo "Ignoring following files/ dir from tar file"
        cat $IGNORE_FILE

    - name: Create tar file
      shell: bash
      env:
        TAR_FILE: "output/repository.tar.gz"
        IGNORE_FILE: "output/ignore_files.txt"
        CHECKOUT_DIR: "git_checkout"
      run: |
          echo "Creating tar file: $TAR_FILE"
          tar --exclude-from="$IGNORE_FILE" -czf "$TAR_FILE" -C "$CHECKOUT_DIR" .
          echo "Tar file created successfully"
          echo "tar file size:"
          ls -lh gitignore.txt | awk '{print $5}'

    - name: Add remote host to known_hosts
      shell: bash
      env:
        REMOTE_HOST: ${{ inputs.remote_host }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts

    - name: Deploy files via rsync
      shell: bash
      env:
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_PASSWORD: ${{ inputs.ssh_password }}
        REMOTE_HOST: ${{ inputs.remote_host }}
        REMOTE_DIR: '/html/deployer'
        TAR_FILE: "output/repository.tar.gz"
      run: |
        echo "Creating remote directory: $REMOTE_DIR"
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$REMOTE_HOST" "mkdir -p '$REMOTE_DIR' || exit 1"
        echo "Uploading tar file to $REMOTE_DIR"
        sshpass -p "$SSH_PASSWORD" rsync -avz --delete "$TAR_FILE" "$SSH_USER@$REMOTE_HOST:$REMOTE_DIR"
        echo "Deployment completed successfully."

    - name: Clean up
      shell: bash
      env:
        TAR_FILE: "output/repository.tar.gz"
        IGNORE_FILE: "output/ignore_files.txt"
        CHECKOUT_DIR: "git_checkout"
      run: |
        echo "Cleaning up temporary files..."
        rm -f "$TAR_FILE"
        rm -f "$IGNORE_FILE"
        rm -rf "$CHECKOUT_DIR"
        echo "Temporary files cleaned up successfully."
        ls -lha

    - name: Run Deployer
      shell: bash
      run: |
        echo "Run Server deployer"
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$REMOTE_HOST" "/html/deployer.sh || exit 1"
