name: 'Deploy Repository via rsync'
description: 'A custom action to deploy a repository to a remote server using rsync.'

inputs:
  ssh_user:
    description: 'The SSH username'
    required: true
  ssh_password:
    description: 'The SSH password'
    required: true
  remote_host:
    description: 'The remote host (IP or domain)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Pre Check
      id: pre_check
      shell: bash
      run: |
        sudo apt-get update -q && sudo apt-get install -y rsync sshpass
        
        mkdir -p ~/.ssh
        ssh-keyscan -H "${{ inputs.remote_host }}" >> ~/.ssh/known_hosts
        
        ACTION_PATH="${{ github.action_path }}"
        TAG_NAME=$(basename "$ACTION_PATH")
        echo "::set-output name=tag::$TAG_NAME"

        echo "::set-output name=tar_file::output/repository.tar.gz"
        echo "::set-output name=checkout_dir::git_checkout"
        echo "::set-output name=action_dir::action_dir"
        echo "::set-output name=ignore_file::action_dir/ignore_files.txt"
        echo "::set-output name=diff_file::output/differences.txt"
        echo "::set-output name=remote_dir::/html/deployer"

    - name: Checkout repository
      with:
        path: ${{ steps.pre_check.outputs.action_dir }}
      uses: actions/checkout@v3

    - name: Checkout Action
      with:
        path: git_action
        repository: narethiya-godaddy/git-deploy-poc
        ref: ${{ steps.pre_check.outputs.tag }}
      uses: actions/checkout@v3

    - name: Create tar file
      shell: bash
      env:
        TAR_FILE: ${{ steps.pre_check.outputs.tar_file }}
        IGNORE_FILE: ${{ steps.pre_check.outputs.ignore_file }}
        CHECKOUT_DIR: ${{ steps.pre_check.outputs.checkout_dir }}
        DIFF_FILE: ${{ steps.pre_check.outputs.diff_file }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_PASSWORD: ${{ inputs.ssh_password }}
        SSH_HOST: ${{ inputs.remote_host }}
      run: |
        EXCLUDE_ARGS=""
        while IFS= read -r line; do
          EXCLUDE_ARGS+="--exclude=$line "
        done < "$IGNORE_FILE"

        echo "Preparing a cleaned list of changed files for sync with the remote server."
        sshpass -p "$SSH_PASSWORD" rsync -av --dry-run --checksum $EXCLUDE_ARGS $CHECKOUT_DIR/ "$SSH_USER@$SSH_HOST:/html/" | grep -v '/$' > $DIFF_FILE
        sed -i '1d;N;$!P;$!D;$d;$d' "${DIFF_FILE}"

        echo "Files to be synchronized:"
        cat "$DIFF_FILE"
        echo "End of list."
        
        cd $CHECKOUT_DIR
        echo "Creating tar file: $TAR_FILE"
        tar -czvf "../$TAR_FILE" -T "../$DIFF_FILE"
        cd ../
        echo "Tar file created successfully."
        echo "tar file size:"

    - name: Deploy files via rsync
      shell: bash
      env:
        TAR_FILE: ${{ steps.pre_check.outputs.tar_file }}
        CHECKOUT_DIR: ${{ steps.pre_check.outputs.checkout_dir }}
        REMOTE_DIR: ${{ steps.pre_check.outputs.remote_dir }}
        SSH_PASSWORD: ${{ inputs.ssh_password }}
        SSH_HOST: ${{ inputs.remote_host }}
        SSH_USER: ${{ inputs.ssh_user }}
      run: |
        echo "Creating remote directory: $REMOTE_DIR"
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "mkdir -p '$REMOTE_DIR' || exit 1"
        echo "Uploading tar file to $REMOTE_DIR"
        REMOTE_TAR_FILE="repository_$(openssl rand -hex 4).tar.gz"
        echo "::set-output name=remote_tar_file::$REMOTE_TAR_FILE"
        echo "REMOTE_TAR_FILE: $REMOTE_TAR_FILE"
        sshpass -p "$SSH_PASSWORD" rsync -avz --delete "$TAR_FILE" "$SSH_USER@$SSH_HOST:$REMOTE_DIR/$REMOTE_TAR_FILE"
        echo "Tar file uploaded successfully."

    - name: Clean up
      shell: bash
      env:
        TAR_FILE: ${{ steps.pre_check.outputs.tar_file }}
        CHECKOUT_DIR: ${{ steps.pre_check.outputs.checkout_dir }}
      run: |
        echo "Cleaning up temporary files..."
        rm -f "$TAR_FILE"
        rm -rf "$CHECKOUT_DIR"
        echo "Temporary files cleaned up successfully."
        ls -lha

    - name: Run Deployer
      shell: bash
      env:
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_PASSWORD: ${{ inputs.ssh_password }}
        SSH_HOST: ${{ inputs.remote_host }}
      run: |
        echo "Run Server deployer"
        echo "tar file name from Env: $REMOTE_TAR_FILE"
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "/html/deployer.sh || exit 1"
